export const demoOperators = [
  {
    name: "Rahim Ahmed",
    email: "demo.driver1@gmail.com",
    phone: "01710000001",
    password: "Driver123!",
    employeeCode: "DRV-001",
    operatorType: "DRIVER" as const,
    licenseNumber: "DL-DEMO-001",
  },
  {
    name: "Karim Ahmed",
    email: "demo.driver2@gmail.com",
    phone: "01710000002",
    password: "Driver123!",
    employeeCode: "DRV-002",
    operatorType: "DRIVER" as const,
    licenseNumber: "DL-DEMO-002",
  },
  {
    name: "Hasan Ahmed",
    email: "demo.driver3@gmail.com",
    phone: "01710000003",
    password: "Driver123!",
    employeeCode: "DRV-003",
    operatorType: "DRIVER" as const,
    licenseNumber: "DL-DEMO-003",
  },
  {
    name: "Sakib Ahmed",
    email: "demo.driver4@gmail.com",
    phone: "01710000004",
    password: "Driver123!",
    employeeCode: "DRV-004",
    operatorType: "DRIVER" as const,
    licenseNumber: "DL-DEMO-004",
  },
  {
    name: "Imran Ahmed",
    email: "demo.driver5@gmail.com",
    phone: "01710000005",
    password: "Driver123!",
    employeeCode: "DRV-005",
    operatorType: "DRIVER" as const,
    licenseNumber: "DL-DEMO-005",
  },

  {
    name: "Arif Ahmed",
    email: "demo.dispatcher1@gmail.com",
    phone: "01710000006",
    password: "Dispatcher123!",
    employeeCode: "DIS-001",
    operatorType: "DISPATCHER" as const,
    licenseNumber: null,
  },
  {
    name: "Nayeem Ahmed",
    email: "demo.dispatcher2@gmail.com",
    phone: "01710000007",
    password: "Dispatcher123!",
    employeeCode: "DIS-002",
    operatorType: "DISPATCHER" as const,
    licenseNumber: null,
  },
];
